### PR TITLE
Adds a module for WhatsApp media tables

### PR DESCRIPTION
**Pull request by JacekPlacek44**
mvt/ios/modules/mixed/__init__.py

### CODE REVIEW

**Comment by botherder** [comment]
Can anyone test this? (And perhaps resolve merge conflicts <3).
Thanks!

**Comment by botherder** [comment]
Can anyone test this? (And perhaps resolve merge conflicts <3).
Thanks!

**Comment by Te-k** [comment]
I don't think this module is needed anymore, it was initially there to also look for data in the ZWAMEDIAITEM table from the WhatsApp application, but the [existing module](https://github.com/mvt-project/mvt/blob/main/mvt/ios/modules/mixed/whatsapp.py) has been extended to also extract data from it. The only limitation is that it would miss media items that do not have a related entry in ZWAMESSAGE, but not sure how to solve that

**Comment by botherder** [comment]
Ok, then I'm closing this PR. Thanks anyway for the contribution.

**Pull request closed without merging**
