### PR TITLE
Add IOC info to README and main docs

### PR DESCRIPTION
**Pull request by pkirkovsky**
#58 and #65

### CODE REVIEW

**Comment by U039b** [comment]
LGTM

**Comment by stman** [comment]
Hello.

Where do we can download those STIX2 files containing the parameters to detect PEGASUS ? It is not specified anywhere in the doc. Thank you.

**Comment by botherder** [comment]
While I do see why in this moment it is important to indicate where to retrieve the STIX2 file for the Pegasus Project investigation, I am conflicted because part of the reason behind choosing STIX2 is to render MVT agnostic to any particular malware. Perhaps it would be useful to have a dedicated page in the documentation where to collect that and other sources of STIX2 definitions, but I would prefer to characterize MVT more explicitly as an agnostic tool that can be used for this and any future investigation.

**Comment by dkg** [comment]
I've just opened #141 to offer a more generic piece of documentation, one that mention's Amnesty's work on Pegasus without elevating it as a singular focus of MVT.  I hope it's useful!

**Comment by botherder** [comment]
Thank you @dkg, I've merged it. Thank you all for this discussion.

**Pull request closed without merging**
